easy_admin:
  site_name: '<a href="/"><img src="/assets/images/logo.png" style="height: 80px" alt="0déchet"></a>'
  formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i'
  design:
        brand_color: '#739377'
        assets:
          css:
            - 'assets/css/admin.css'
          favicon: '/assets/images/logo-mobile.png'
        menu:
            - { entity: 'Category', label: 'Catégories' }
            - { entity: 'SubCategory', label: 'Sous-catégories', icon: 'list' }
            - { entity: 'Type', label: 'Types', icon: 'list-ol' }
            - { entity: 'Recipe', label: 'Recettes', icon: 'file-image' }
            - { entity: 'Rate', label: 'Notes', icon: 'star' }
            - { entity: 'Comment', label: 'Commentaires', icon: 'file-text' }
            - { entity: 'User', label: 'Utilisateurs', icon: 'user' }
            - { label: 'Retour sur le site', route: 'main_home', icon: 'leaf' }
  user:
        display_avatar: false
        # avatar_property_path: 'image'
        # base_path: '%app.path.user_images%/'
      
  list:
        max_results: 20
  entities:
    Category:
            class: App\Entity\Category
            label: 'Catégories'
            list:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Nom de la catégorie' }
                    - { property: 'sub_categories', label: 'Sous-catégorie' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'createdAt', label: 'Créé le' }
                    - { property: 'updatedAt', label: 'Modifié le' }
            form:
                fields: 
                    - { property: 'name', label: 'Nom de la catégorie', type_options: { required: true } }
            new:
                title: 'Ajouter une catégorie'
            edit:
                title: 'Modifier une catégorie'
    SubCategory:
            class: App\Entity\SubCategory
            label: 'Sous-catégories'
            list:
                fields: 
                    - 'id'
                    - { property: 'name', label: 'Nom de la sous-catégorie' }
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'types', label: 'Type' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'createdAt', label: 'Créé le' }
                    - { property: 'updatedAt', label: 'Modifié le' }
            form:
                fields: 
                    - { property: 'name', label: 'Nom de la sous-catégorie', type_options: { required: true } }
                    - { property: 'category', label: 'Catégorie' }
            new:
                title: 'Ajouter une sous-catégorie'
            edit:
                title: 'Modifier une sous-catégorie'
    Type:
            class: App\Entity\Type
            label: 'Types'
            list:
                fields: 
                    - 'id'
                    - { property: 'name', label: 'Type de produit' }
                    - { property: 'subCategory', label: 'Sous-catégorie' }
                    - { property: 'recipes', label: 'Recette' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'createdAt', label: 'Créé le' }
                    - { property: 'updatedAt', label: 'Modifié le' }
            form:
                fields: 
                    - { property: 'name', label: 'Type de produit', type_options: { required: true } }
                    - { property: 'subCategory', label: 'Sous-catégorie' }
            new:
                title: 'Ajouter un type'
            edit:
                title: 'Modifier un type'
    Recipe:
            class: App\Entity\Recipe
            image_base_path: '/assets/images/'
            label: 'Recettes'
            list:
                fields: 
                    - 'id'
                    - { property: 'name', label: 'Nom de la recette' }
                    - { property: 'duration', label: 'Durée' }
                    - { property: 'difficulty', label: 'Difficulté' }
                    - { property: 'conservation', label: 'Conservation' }
                    - { property: 'image', type: 'image', label: 'Image de la recette', base_path: '%app.path.recipe_images%' }
                    - { property: 'status', label: 'Status' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'comments', label: 'Commentaire' }
                    - { property: 'averageRate', label: 'Note' }
                    - { property: 'createdAt', label: 'Créé le' }
                    - { property: 'updatedAt', label: 'Modifié le' }
            form:
                fields: 
                    - { property: 'name', label: 'Nom de la recette', type_options: { required: true } }
                    - { property: 'ingredient', label: 'Ingrédients', type_options: { required: true } }
                    - { property: 'equipement', label: 'Matériels' }
                    - { property: 'content', label: 'Détail de la préparation', type_options: { required: true } }
                    - { property: 'duration', label: 'Durée', type: 'integer', type_options: { required: true, } }
                    - { property: 'difficulty', label: 'Difficulté', type: 'choice', type_options: {expanded: false, multiple: false, required: true, choices: {'Débutant': '1', 'Intermédiaire': '2', 'Expert': '3'}} }
                    - { property: 'conservation', label: 'Temps le conservation', type: 'choice', type_options: {expanded: false, multiple: false, choices: {'1 semaine': '7', '2 semaines': '14', '1 mois':'30', '2 mois': '60', '3 mois': '90', '6 mois': '180'}} }
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo de la recette' }
                    - { property: 'type', label: 'Type de recette', type_options: { required: true } }
                    - { property: 'status', label: 'Status' }
                    - { property: 'user', label: 'Utilisateur' }
            new:
                title: 'Ajouter une recette'
            edit:
                title: 'Modifier une recette'
    Rate:
            class: App\Entity\Rate
            label: 'Notes'
            list:
                fields: 
                    - 'id'
                    - { property: 'rate', label: 'Note' }
                    - { property: 'recipe', label: 'Recette' }
                    - { property: 'user', label: 'Utilisateur' }
            form:
                fields: 
                    - { property: 'rate', label: 'Note', type: 'choice', type_options: {expanded: false, multiple: false, choices: {'1 étoile': '1', '2 étoiles': '2', '3 étoiles': '3', '4 étoiles': '4', '5 étoiles': '5' }}  }
                    - { property: 'recipe', label: 'Recette' }
                    - { property: 'user', label: 'Utilisateur' }
            new:
                title: 'Ajouter une note'
            edit:
                title: 'Modifier une note'
    Comment:
            class: App\Entity\Comment
            label: 'Commentaires'
            list:
              fields: 
                  - 'id'
                  - { property: 'title', label: 'Titre du commentaire' }
                  - { property: 'recipe', label: 'Recette' }
                  - { property: 'user', label: 'Utilisateur' }
                  - { property: 'status', label: 'Status' }
                  - { property: 'createdAt', label: 'Créé le' }
                  - { property: 'updatedAt', label: 'Modifié le' }
            form:
              fields: 
                  - { property: 'title', label: 'Titre du commentaire' }
                  - { property: 'content', label: 'Commentaire' }
                  - { property: 'recipe', label: 'Recette' }
                  - { property: 'user', label: 'Utilisateur' }
                  - { property: 'status', label: 'Status' }
            new:
                title: 'Ajouter un commentaire'
            edit:
                title: 'Modifier un commentaire'
    User:
            class: App\Entity\User
            label: 'Utilisateurs'
            icon: 'user'
            list:
              fields: 
                  - 'id'
                  - { property: 'email', label: 'Email' }
                  - { property: 'username', label: 'Pseudo' }
                  - { property: 'roles', label: 'Rôle' }
                  - { property: 'image', type: 'image', label: 'Photo de profil', base_path: '%app.path.user_images%' }
                  - { property: 'recipes', label: 'Recette ajouté' }
                  - { property: 'comments', label: 'Commentaire lié' }
                  - { property: 'createdAt', label: 'Créé le' }
                  - { property: 'updatedAt', label: 'Modifié le' }
            new:
              title: 'Ajouter un utilisateur'
              fields: 
                  - { property: 'username', label: "Nom d'utilisateur", type_options: { required: true } }
                  - { property: 'email', label: 'Email', type: 'email', type_options: { required: true } }
                  - { property: 'password', type: 'password', label: 'Mot de passe', help: "Votre mot de passe doit être compris entre 8 et 20 caractères et doit contenir au moins une minuscle, une majuscule, un chiffre et un des caractères spéciaux $ @ % * + - _ !", type_options: { required: true, mapped: true } }
                  - { property: 'roles', label: 'Rôles', type: choice, 
                        type_options: {expanded: true, multiple: true, 
                          choices: {'Utilisateur':'ROLE_USER', 
                                    'Administrateur':'ROLE_ADMIN'}}}
            edit:
              title: 'Modifier un utilisateur'
              fields: 
                  - { property: 'username', label: "Nom d'utilisateur", type_options: { required: true } }
                  - { property: 'email', label: 'Email', type: 'email', type_options: { required: true } }
                  - { property: 'imageFile', type: 'vich_image', label: 'Modifier la photo de profil' }
                  - { property: 'recipes', label: 'Recette ajouté' }
                  - { property: 'comments', label: 'Commentaire lié' }
                  - { property: 'roles', label: 'Rôles', type: choice, 
                        type_options: {expanded: true, multiple: true, 
                          choices: {'Utilisateur':'ROLE_USER', 
                                    'Administrateur':'ROLE_ADMIN'}}}
